# 查询域名信息

需求描述：
- 一个域名，只有一次成功的 whois 或 rdap 接口查询
- 不做命令依赖检查
- 1～N 查询接口
  - 接口超时使用下一个，直至查询成功返回信息
  - 全部查询失败，返回告知信息
  - 接口 https://rdap.verisign.com/com/v1/domain/，https://rdap.markmonitor.com/rdap/domain/
  - 接口可以方便添加删减
- rdap.sh [domain]
  - 只返回 expiration，last changed ，registration，nameservers
  - 输入 domain.com 或 a.domain.com 或 a.a.domain.com，提取 domain.com 查询
  - 返回信息两列
    - 第一列 eventAction，第二列 eventDate（格式处理为 2028-10-11）
    - 或者第一列 nameservers，第二列 ldhName 值，多个值，只输出第一个
- 优先使用 whois 命令查询
  - whois 查询失败判断条件，取不到 “Registry Expiry Date” 值
  - whois 查询失败，间隔 N 秒后（与文本域名列表查询间隔秒相同）重试，最多查询 3 次
  - whois 查询无法获取到值，使用 rdap 接口查询
  - rdap 接口只有解析到 expiration 值才视为成功；HTTP 成功但无 expiration 值，继续尝试下一个接口
  - rdap 接口查询失败或无法解析 expiration 值，间隔 N 秒后重试，最多查询 3 轮
  - 输出格式与 rdap 保持一致，rdap whois 字段对应：
    - registration “Creation Date”
    - expiration “Registry Expiry Date”
    - last changed “ Updated Date”
    - nameservers “Name Server”
- rdap.sh [-v] <domain> 完整输出
  - whois 查询完整输出。
  - rdap 查询，jq 高亮完整输出。
- rdap.sh [-f [file_path]] [-d [number]]
  - [-f file_path] 指定文本读取域名列表查询
    - file_path 不存在或没指定，读取脚本同目录 rdap.sh.txt
    - 约定 file_path 为一列域名
    - 使用域名查询，查询结果写入 file_path.check.txt 中
      - 同一次运行内仅缓存已成功获取的根域名 expiration 值；失败不缓存，避免一次限流导致同根域名后续行直接失败
      - 约定 file_path.check.txt 为 三列
        - 第一列 域名
        - 第二列 expiration 值，格式处理为（2028-10-11）
          - 获取不到该值，该值就为 X
        - 第三列 域名还有还有多少天到期
          - 第二列值为 X，第三列值为空
    - 存在一个变量，控制域名查询间隔秒（缺省 3s）
    - 查询结束，按第三列升序排序。
      - 置顶第三列值为空的行
    - file_path.check.txt 该文件存在覆盖不提醒
  - [-d [number]] 筛选还有多少天到期的域名
    - number（缺省 30 天）天内到期域名，写入脚本同目录 file_path.check.[number]d.txt 中
    - file_path.check.[number]d.txt 约定格式与 file_path.check.txt 一致
      - 与 file_path.check.txt 同规则排序
    - file_path.check.n[number].txt 该文件存在覆盖不提醒。
  - 最终 file_path.check.txt file_path.check.[number]d.txt 文件，列对齐，更加直观。
